# Generated by Django 6.0.6 on 2026-08-06 12:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        ('projects', '0002_project_tasks_fo104'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTaskDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, db_index=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('dependency_type', models.CharField(choices=[('finish_to_start', 'Finish to Start')], default='finish_to_start', max_length=32)),
                ('predecessor_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='successor_dependencies', to='projects.projecttask')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_dependencies', to='projects.project')),
                ('successor_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecessor_dependencies', to='projects.projecttask')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_task_dependencies', to='master_data.tenant')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['predecessor_task'], name='proj_dep_pred_idx'), models.Index(fields=['successor_task'], name='proj_dep_succ_idx'), models.Index(fields=['project'], name='proj_dep_project_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('predecessor_task', 'successor_task'), name='unique_active_project_task_dependency')],
            },
        ),
    ]
