# Generated by Django 6.0.6 on 2026-08-06 23:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import ROUND_HALF_UP, Decimal

from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


INCLUDED_STATUSES = frozenset(
    {"not_started", "in_progress", "blocked", "on_hold", "completed"}
)


def _round_pct(value: Decimal) -> Decimal:
    quantized = value.quantize(Decimal("1"), rounding=ROUND_HALF_UP)
    if quantized < 0:
        quantized = Decimal("0")
    elif quantized > 100:
        quantized = Decimal("100")
    return Decimal(f"{int(quantized)}.00")


def _task_contribution(task) -> Decimal:
    if task.is_milestone:
        if task.status == "completed":
            return Decimal("100.00")
        return Decimal("0.00")
    return Decimal(str(task.progress_percentage or "0.00"))


def backfill_project_progress(apps, schema_editor):
    """Idempotent FO-107 backfill: recalculate % and migration_rebuild snapshot."""
    Project = apps.get_model("projects", "Project")
    ProjectTask = apps.get_model("projects", "ProjectTask")
    ProjectProgressSnapshot = apps.get_model("projects", "ProjectProgressSnapshot")

    today = timezone.localdate()

    for project in Project.objects.filter(is_deleted=False).iterator():
        tasks = list(
            ProjectTask.objects.filter(project_id=project.id, is_deleted=False)
        )
        included = [t for t in tasks if t.status in INCLUDED_STATUSES]

        if included:
            total = sum((_task_contribution(t) for t in included), Decimal("0.00"))
            pct = _round_pct(total / Decimal(len(included)))
        else:
            pct = Decimal("0.00")

        completed_count = sum(1 for t in included if t.status == "completed")
        blocked_count = sum(1 for t in included if t.status == "blocked")
        delayed_count = 0
        for task in included:
            if (
                task.status not in ("completed", "cancelled")
                and task.planned_end is not None
                and task.planned_end < today
                and task.actual_end is None
            ):
                delayed_count += 1

        current = Decimal(str(project.completion_percentage or "0.00"))
        if current != pct:
            project.completion_percentage = pct
            project.save(update_fields=["completion_percentage"])

        latest = (
            ProjectProgressSnapshot.objects.filter(
                project_id=project.id,
                is_deleted=False,
            )
            .order_by("-recorded_at", "-created_at")
            .first()
        )
        if latest is not None and Decimal(str(latest.completion_percentage)) == pct:
            continue

        ProjectProgressSnapshot.objects.create(
            tenant_id=project.tenant_id,
            project_id=project.id,
            completion_percentage=pct,
            included_task_count=len(included),
            completed_task_count=completed_count,
            blocked_task_count=blocked_count,
            delayed_task_count=delayed_count,
            recorded_at=timezone.now(),
            source="migration_rebuild",
        )


def noop_reverse(apps, schema_editor):
    # Snapshots remain; do not destroy history on reverse.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0001_initial"),
        ("projects", "0004_project_notes_issues_timeline_fo106"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectProgressSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                (
                    "completion_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("included_task_count", models.IntegerField(default=0)),
                ("completed_task_count", models.IntegerField(default=0)),
                ("blocked_task_count", models.IntegerField(default=0)),
                ("delayed_task_count", models.IntegerField(default=0)),
                (
                    "recorded_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("task_created", "Task Created"),
                            ("task_progress_changed", "Task Progress Changed"),
                            ("task_status_changed", "Task Status Changed"),
                            ("task_cancelled", "Task Cancelled"),
                            ("task_deleted", "Task Deleted"),
                            ("task_restored", "Task Restored"),
                            ("manual_recalculation", "Manual Recalculation"),
                            ("migration_rebuild", "Migration Rebuild"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_snapshots",
                        to="projects.project",
                    ),
                ),
                (
                    "related_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="progress_snapshots",
                        to="projects.projecttask",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_progress_snapshots",
                        to="master_data.tenant",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_progress_snapshots_triggered",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "recorded_at"],
                        name="proj_prog_snap_proj_rec_idx",
                    )
                ],
            },
        ),
        migrations.RunPython(backfill_project_progress, noop_reverse),
    ]
