# Generated by Django 6.0.6 on 2026-08-07 00:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm_tickets', '0007_fo096_employee_intake_foundation'),
        ('inspection', '0001_initial'),
        ('maintenance', '0005_work_order_source_ticket'),
        ('master_data', '0001_initial'),
        ('projects', '0005_project_progress_fo107'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectOperationalLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, db_index=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('link_type', models.CharField(choices=[('fm_ticket', 'FM Ticket'), ('maintenance_work_order', 'Maintenance Work Order'), ('inspection', 'Inspection')], db_index=True, max_length=32)),
                ('relationship', models.CharField(choices=[('related', 'Related'), ('source', 'Source'), ('execution', 'Execution'), ('corrective_action', 'Corrective Action'), ('evidence', 'Evidence'), ('follow_up', 'Follow Up')], db_index=True, default='related', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('fm_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_operational_links', to='fm_tickets.fmticket')),
                ('inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_operational_links', to='inspection.inspection')),
                ('maintenance_work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_operational_links', to='maintenance.maintenanceworkorder')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_links', to='projects.project')),
                ('project_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_links', to='projects.projecttask')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_operational_links', to='master_data.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'link_type'], name='proj_op_link_type_idx'), models.Index(fields=['project_task'], name='proj_op_link_task_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('fm_ticket__isnull', False), ('maintenance_work_order__isnull', True), ('inspection__isnull', True), ('link_type', 'fm_ticket')), models.Q(('fm_ticket__isnull', True), ('maintenance_work_order__isnull', False), ('inspection__isnull', True), ('link_type', 'maintenance_work_order')), models.Q(('fm_ticket__isnull', True), ('maintenance_work_order__isnull', True), ('inspection__isnull', False), ('link_type', 'inspection')), _connector='OR'), name='proj_op_link_exactly_one_target'), models.UniqueConstraint(condition=models.Q(('fm_ticket__isnull', False), ('is_deleted', False)), fields=('project', 'fm_ticket'), name='unique_active_project_fm_ticket_link'), models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('maintenance_work_order__isnull', False)), fields=('project', 'maintenance_work_order'), name='unique_active_project_mwo_link'), models.UniqueConstraint(condition=models.Q(('inspection__isnull', False), ('is_deleted', False)), fields=('project', 'inspection'), name='unique_active_project_inspection_link')],
            },
        ),
    ]
