# Generated by Django 6.0.6 on 2026-07-27 08:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("master_data", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, db_index=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                ("original_filename", models.CharField(max_length=255)),
                ("display_filename", models.CharField(max_length=255)),
                ("storage_key", models.CharField(max_length=512, unique=True)),
                ("declared_content_type", models.CharField(blank=True, max_length=100)),
                ("validated_content_type", models.CharField(max_length=100)),
                ("extension", models.CharField(max_length=20)),
                ("size_bytes", models.PositiveBigIntegerField()),
                ("checksum_sha256", models.CharField(db_index=True, max_length=64)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("image_evidence", "Image evidence"),
                            ("document", "Document"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("retired", "Retired")],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attachments",
                        to="master_data.tenant",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="AttachmentHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.UUIDField(blank=True, db_index=True, null=True)),
                ("updated_by", models.UUIDField(blank=True, null=True)),
                ("deleted_by", models.UUIDField(blank=True, null=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("downloaded", "Downloaded"),
                            ("deleted", "Deleted"),
                            ("access_denied", "Access denied"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("attachment_id_snapshot", models.UUIDField(db_index=True)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attachment_history_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "attachment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_entries",
                        to="attachments.attachment",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attachment_history_entries",
                        to="master_data.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(
                fields=["tenant", "status", "-created_at"],
                name="attach_tenant_status_created",
            ),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(
                fields=["tenant", "uploaded_by", "-created_at"],
                name="attach_tenant_uploader_created",
            ),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(
                fields=["tenant", "is_deleted", "-created_at"],
                name="attach_tenant_deleted_created",
            ),
        ),
        migrations.AddIndex(
            model_name="attachmenthistory",
            index=models.Index(
                fields=["tenant", "action", "-created_at"],
                name="attach_hist_tenant_action",
            ),
        ),
    ]
