# Generated by Django 5.2.8 on 2026-07-28 05:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_attachment_foundation'),
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='owner_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Owning business object UUID. Null when unlinked.', null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='owner_type',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Owning business object type (e.g. fm_ticket). Blank = unlinked.', max_length=64),
        ),
        migrations.AddField(
            model_name='attachment',
            name='visibility',
            field=models.CharField(choices=[('internal_only', 'Internal only'), ('requester_visible', 'Requester visible')], db_index=True, default='internal_only', help_text='Audience visibility. Defaults to internal_only for safety.', max_length=32),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['tenant', 'owner_type', 'owner_id', 'status', '-created_at'], name='attach_owner_status_crt'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['tenant', 'owner_type', 'owner_id', 'visibility', '-created_at'], name='attach_owner_vis_crt'),
        ),
    ]
