# Generated by Django 6.0.6 on 2026-07-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancecompletion",
            name="actual_hours",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="maintenancestatushistory",
            name="action",
            field=models.CharField(
                choices=[
                    ("submit", "Submit"),
                    ("assign", "Assign"),
                    ("start", "Start"),
                    ("hold", "Hold"),
                    ("resume", "Resume"),
                    ("complete", "Complete"),
                    ("cancel", "Cancel"),
                    ("reopen", "Reopen"),
                    ("system", "System"),
                ],
                default="system",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="maintenancestatushistory",
            name="reason",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="maintenancestatushistory",
            name="from_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("draft", "Draft"),
                    ("open", "Open"),
                    ("assigned", "Assigned"),
                    ("in_progress", "In Progress"),
                    ("on_hold", "On Hold"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("reopened", "Reopened"),
                    ("closed", "Closed"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="maintenancestatushistory",
            name="to_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("open", "Open"),
                    ("assigned", "Assigned"),
                    ("in_progress", "In Progress"),
                    ("on_hold", "On Hold"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("reopened", "Reopened"),
                    ("closed", "Closed"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="maintenanceworkorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("open", "Open"),
                    ("assigned", "Assigned"),
                    ("in_progress", "In Progress"),
                    ("on_hold", "On Hold"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("reopened", "Reopened"),
                    ("closed", "Closed"),
                ],
                db_index=True,
                default="open",
                max_length=20,
            ),
        ),
    ]
