# Generated by Django 6.0.6 on 2026-07-07 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_assignment_tenants(apps, schema_editor):
    assignment_model = apps.get_model("maintenance", "MaintenanceAssignment")
    for assignment in assignment_model.objects.select_related("work_order").all():
        assignment.tenant_id = assignment.work_order.tenant_id
        assignment.save(update_fields=("tenant",))


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0002_maintenancecompletion_actual_hours_and_more"),
        ("master_data", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenanceassignment",
            name="assignment_status",
            field=models.CharField(
                choices=[
                    ("assigned", "Assigned"),
                    ("reassigned", "Reassigned"),
                    ("unassigned", "Unassigned"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                    ("completed", "Completed"),
                ],
                db_index=True,
                default="assigned",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="maintenanceassignment",
            name="assignment_type",
            field=models.CharField(
                choices=[
                    ("technician", "Technician"),
                    ("supervisor", "Supervisor"),
                    ("combined", "Technician and Supervisor"),
                    ("unassigned", "Unassigned"),
                ],
                default="technician",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="maintenanceassignment",
            name="previous_assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="previous_maintenance_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="maintenanceassignment",
            name="previous_supervisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="previous_maintenance_supervision_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="maintenanceassignment",
            name="reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="maintenanceassignment",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="maintenance_supervision_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="maintenanceassignment",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="maintenance_assignments",
                to="master_data.tenant",
            ),
        ),
        migrations.RunPython(populate_assignment_tenants, migrations.RunPython.noop),
    ]
