# Generated by Django 6.0.6 on 2026-07-07 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_sla_escalation_foundation(apps, schema_editor):
    sla_model = apps.get_model("maintenance", "MaintenanceSLA")
    escalation_model = apps.get_model("maintenance", "MaintenanceEscalation")
    rules = {
        "critical": (30, 240),
        "high": (60, 480),
        "medium": (240, 1440),
        "low": (480, 2880),
    }
    for sla in sla_model.objects.select_related("work_order").all():
        sla.tenant_id = sla.work_order.tenant_id
        sla.priority = sla.work_order.priority
        sla.response_target_minutes, sla.completion_target_minutes = rules[sla.priority]
        sla.save(
            update_fields=(
                "tenant",
                "priority",
                "response_target_minutes",
                "completion_target_minutes",
            )
        )
    sla_by_work_order = dict(sla_model.objects.values_list("work_order_id", "id"))
    for escalation in escalation_model.objects.select_related("work_order").all():
        escalation.tenant_id = escalation.work_order.tenant_id
        escalation.sla_id = sla_by_work_order.get(escalation.work_order_id)
        escalation.status = "open" if escalation.is_active else "resolved"
        escalation.save(update_fields=("tenant", "sla", "status"))


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0003_maintenanceassignment_assignment_status_and_more"),
        ("master_data", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenanceescalation",
            name="acknowledged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="maintenanceescalation",
            name="acknowledged_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="maintenance_escalations_acknowledged",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="maintenanceescalation",
            name="escalation_type",
            field=models.CharField(
                choices=[
                    ("response_warning", "Response Warning"),
                    ("response_breach", "Response Breach"),
                    ("completion_warning", "Completion Warning"),
                    ("completion_breach", "Completion Breach"),
                ],
                db_index=True,
                default="completion_breach",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="maintenanceescalation",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="maintenanceescalation",
            name="sla",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="escalations",
                to="maintenance.maintenancesla",
            ),
        ),
        migrations.AddField(
            model_name="maintenanceescalation",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("acknowledged", "Acknowledged"),
                    ("resolved", "Resolved"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="open",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="maintenanceescalation",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="maintenance_escalations",
                to="master_data.tenant",
            ),
        ),
        migrations.AddField(
            model_name="maintenancesla",
            name="completion_breached",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="maintenancesla",
            name="completion_target_minutes",
            field=models.PositiveIntegerField(default=1440),
        ),
        migrations.AddField(
            model_name="maintenancesla",
            name="last_recalculated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="maintenancesla",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="maintenancesla",
            name="response_breached",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="maintenancesla",
            name="response_target_minutes",
            field=models.PositiveIntegerField(default=240),
        ),
        migrations.AddField(
            model_name="maintenancesla",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="maintenance_sla_records",
                to="master_data.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="maintenancesla",
            name="sla_status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("within_sla", "Within SLA"),
                    ("at_risk", "At Risk"),
                    ("breached", "Breached"),
                    ("met", "Met"),
                    ("missed", "Missed"),
                    ("not_applicable", "Not Applicable"),
                    ("warning", "Warning"),
                    ("paused", "Paused"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="not_applicable",
                max_length=20,
            ),
        ),
        migrations.RunPython(
            populate_sla_escalation_foundation,
            migrations.RunPython.noop,
        ),
    ]
