# Generated by Django 5.2.8 on 2026-07-14 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm_tickets', '0002_fmticket_first_responded_at_and_more'),
        ('maintenance', '0004_maintenanceescalation_acknowledged_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceworkorder',
            name='source_ticket',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_work_order', to='fm_tickets.fmticket'),
        ),
    ]
