export const API_ENDPOINTS = {
  health: "/health/",
  auth: {
    login: "/auth/login/",
    refresh: "/auth/refresh/",
    logout: "/auth/logout/",
    me: "/auth/me/",
  },
  accessControl: {
    roles: "/access-control/roles/",
    role: (id: string) => `/access-control/roles/${id}/`,
    permissions: "/access-control/permissions/",
    permission: (id: string) => `/access-control/permissions/${id}/`,
    mePermissions: "/access-control/me/permissions/",
  },
  dashboard: {
    foundationSummary: "/dashboard/foundation-summary/",
  },
  masterData: {
    tenants: "/master-data/tenants/",
    tenant: (id: string) => `/master-data/tenants/${id}/`,
    organizations: "/master-data/organizations/",
    organization: (id: string) => `/master-data/organizations/${id}/`,
    departments: "/master-data/departments/",
    department: (id: string) => `/master-data/departments/${id}/`,
    buildings: "/master-data/buildings/",
    building: (id: string) => `/master-data/buildings/${id}/`,
    floors: "/master-data/floors/",
    floor: (id: string) => `/master-data/floors/${id}/`,
    areas: "/master-data/areas/",
    area: (id: string) => `/master-data/areas/${id}/`,
    assetTypes: "/master-data/asset-types/",
    assetType: (id: string) => `/master-data/asset-types/${id}/`,
    assets: "/master-data/assets/",
    asset: (id: string) => `/master-data/assets/${id}/`,
  },
  fmTickets: {
    tickets: "/fm-tickets/tickets/",
    ticket: (id: string) => `/fm-tickets/tickets/${id}/`,
    comments: (id: string) => `/fm-tickets/tickets/${id}/comments/`,
    history: (id: string) => `/fm-tickets/tickets/${id}/history/`,
    escalations: (id: string) => `/fm-tickets/tickets/${id}/escalations/`,
    escalate: (id: string) => `/fm-tickets/tickets/${id}/escalate/`,
    assign: (id: string) => `/fm-tickets/tickets/${id}/assign/`,
    changeStatus: (id: string) => `/fm-tickets/tickets/${id}/change-status/`,
  },
  maintenance: {
    dashboard: "/maintenance/work-orders/dashboard/",
    workOrders: "/maintenance/work-orders/",
    workOrder: (id: string) => `/maintenance/work-orders/${id}/`,
    history: (id: string) => `/maintenance/work-orders/${id}/history/`,
    submit: (id: string) => `/maintenance/work-orders/${id}/submit/`,
    assign: (id: string) => `/maintenance/work-orders/${id}/assign/`,
    reassign: (id: string) => `/maintenance/work-orders/${id}/reassign/`,
    unassign: (id: string) => `/maintenance/work-orders/${id}/unassign/`,
    assignments: (id: string) => `/maintenance/work-orders/${id}/assignments/`,
    assignmentCandidates: (id: string) =>
      `/maintenance/work-orders/${id}/assignment-candidates/`,
    sla: (id: string) => `/maintenance/work-orders/${id}/sla/`,
    recalculateSla: (id: string) =>
      `/maintenance/work-orders/${id}/sla/recalculate/`,
    escalations: (id: string) => `/maintenance/work-orders/${id}/escalations/`,
    acknowledgeEscalation: (workOrderId: string, escalationId: string) =>
      `/maintenance/work-orders/${workOrderId}/escalations/${escalationId}/acknowledge/`,
    resolveEscalation: (workOrderId: string, escalationId: string) =>
      `/maintenance/work-orders/${workOrderId}/escalations/${escalationId}/resolve/`,
    start: (id: string) => `/maintenance/work-orders/${id}/start/`,
    hold: (id: string) => `/maintenance/work-orders/${id}/hold/`,
    resume: (id: string) => `/maintenance/work-orders/${id}/resume/`,
    complete: (id: string) => `/maintenance/work-orders/${id}/complete/`,
    cancel: (id: string) => `/maintenance/work-orders/${id}/cancel/`,
    reopen: (id: string) => `/maintenance/work-orders/${id}/reopen/`,
  },
} as const;
