# Generated by Django 6.0.6 on 2026-07-06 03:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FmTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, db_index=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('ticket_number', models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('hvac', 'HVAC'), ('civil', 'Civil'), ('safety', 'Safety'), ('cleaning', 'Cleaning'), ('security', 'Security'), ('other', 'Other')], default='other', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=20)),
                ('source', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('admin', 'Admin'), ('inspection', 'Inspection'), ('system', 'System')], default='web', max_length=20)),
                ('reported_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fm_tickets', to='master_data.area')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fm_tickets', to='master_data.asset')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_fm_tickets', to=settings.AUTH_USER_MODEL)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fm_tickets', to='master_data.building')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fm_tickets', to='master_data.department')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fm_tickets', to='master_data.floor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fm_tickets', to='master_data.organization')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_fm_tickets', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fm_tickets', to='master_data.tenant')),
            ],
            options={
                'ordering': ['-reported_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FmTicketComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, db_index=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('body', models.TextField()),
                ('is_internal', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fm_ticket_comments', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='fm_tickets.fmticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FmTicketHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, db_index=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fm_ticket_history_entries', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='fm_tickets.fmticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FmTicketStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, db_index=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('from_status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], max_length=20, null=True)),
                ('to_status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('changed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fm_ticket_status_changes', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history_entries', to='fm_tickets.fmticket')),
            ],
            options={
                'ordering': ['changed_at', 'created_at'],
            },
        ),
    ]
