# Generated by Django 5.2.8 on 2026-07-30 03:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_fm_ticket_owner_visibility'),
        ('fm_tickets', '0002_fmticket_first_responded_at_and_more'),
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AITicketAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, db_index=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('queued_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('model_name', models.CharField(blank=True, default='placeholder', max_length=100)),
                ('model_version', models.CharField(blank=True, default='v0', max_length=50)),
                ('result_json', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_fm_ticket_ai_analyses', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fm_ticket_ai_analyses', to='master_data.tenant')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='fm_tickets.fmticket')),
            ],
            options={
                'ordering': ['-queued_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AITicketAnalysisAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, db_index=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_attachments', to='fm_tickets.aiticketanalysis')),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fm_ticket_ai_analysis_links', to='attachments.attachment')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='aiticketanalysis',
            index=models.Index(fields=['tenant', 'ticket', '-queued_at'], name='fm_ai_tenant_ticket_queued'),
        ),
        migrations.AddIndex(
            model_name='aiticketanalysis',
            index=models.Index(fields=['tenant', 'status', '-queued_at'], name='fm_ai_tenant_status_queued'),
        ),
        migrations.AddConstraint(
            model_name='aiticketanalysisattachment',
            constraint=models.UniqueConstraint(fields=('analysis', 'attachment'), name='uniq_fm_ai_analysis_attachment'),
        ),
    ]
