# Generated by Django 5.2.8 on 2026-07-30 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm_tickets', '0003_aiticketanalysis_foundation'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiticketanalysis',
            name='attempt_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aiticketanalysis',
            name='correlation_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='aiticketanalysis',
            name='error_code',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='aiticketanalysis',
            name='input_byte_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiticketanalysis',
            name='input_image_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiticketanalysis',
            name='prompt_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='aiticketanalysis',
            name='provider',
            field=models.CharField(blank=True, db_index=True, default='placeholder', max_length=50),
        ),
        migrations.AddField(
            model_name='aiticketanalysis',
            name='retryable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiticketanalysis',
            name='schema_version',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
