# Generated by Django 6.0.6 on 2026-08-03 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm_tickets', '0004_aiticketanalysis_gemini_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiticketanalysis',
            name='decision',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('modified', 'Modified'), ('ignored', 'Ignored')], db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='aiticketanalysis',
            name='decision_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiticketanalysis',
            name='decision_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fm_ticket_ai_recommendation_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiticketanalysis',
            name='decision_recommended_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aiticketanalysis',
            name='decision_recommended_priority',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='aiticketanalysis',
            name='final_category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='aiticketanalysis',
            name='final_priority',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
