# Generated by Django 6.0.6 on 2026-08-04 22:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm_tickets', '0005_aiticketanalysis_recommendation_decision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAdminConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, db_index=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, default='', max_length=50)),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('enabled', models.BooleanField(blank=True, null=True)),
                ('timeout_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('max_images', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_upload_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('retry_attempts', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('store_raw_response', models.BooleanField(blank=True, null=True)),
                ('flag_image_analysis', models.BooleanField(default=True)),
                ('flag_recommendation_engine', models.BooleanField(default=True)),
                ('flag_executive_dashboard', models.BooleanField(default=True)),
                ('flag_similar_cases', models.BooleanField(default=True)),
                ('flag_attention_center', models.BooleanField(default=True)),
                ('flag_operational_insights', models.BooleanField(default=True)),
                ('confidence_threshold', models.FloatField(blank=True, null=True)),
                ('health_warning_threshold', models.PositiveIntegerField(blank=True, null=True)),
                ('health_critical_threshold', models.PositiveIntegerField(blank=True, null=True)),
                ('attention_warning_threshold', models.PositiveIntegerField(blank=True, null=True)),
                ('attention_critical_threshold', models.PositiveIntegerField(blank=True, null=True)),
                ('acceptance_healthy_rate', models.FloatField(blank=True, null=True)),
                ('override_warning_rate', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'AI admin config',
                'verbose_name_plural': 'AI admin config',
            },
        ),
        migrations.CreateModel(
            name='AIAdminAuditEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.UUIDField(blank=True, db_index=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('deleted_by', models.UUIDField(blank=True, null=True)),
                ('actor_email', models.EmailField(blank=True, default='', max_length=254)),
                ('changed_field', models.CharField(db_index=True, max_length=100)),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('scope', models.CharField(db_index=True, default='global', max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_admin_audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'changed_field'], name='fm_ai_admin_audit_created')],
            },
        ),
    ]
