# Generated by Django 6.0.6 on 2026-08-05 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm_tickets', '0006_fo093_ai_admin_governance'),
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fmticket',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fm_tickets', to='master_data.building'),
        ),
        migrations.AlterField(
            model_name='fmticket',
            name='category',
            field=models.CharField(choices=[('unclassified', 'Unclassified'), ('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('hvac', 'HVAC'), ('civil', 'Civil'), ('safety', 'Safety'), ('cleaning', 'Cleaning'), ('security', 'Security'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='fmticket',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='fmticket',
            name='priority',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20),
        ),
    ]
