# Generated by Django 6.0.6 on 2026-08-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm_tickets', '0007_fo096_employee_intake_foundation'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiticketanalysis',
            name='admin_diagnostic_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aiticketanalysis',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='aiticketanalysis',
            name='provider_diagnostics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='aiticketanalysis',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('waiting_for_retry', 'Waiting for Retry'), ('retrying', 'Retrying'), ('completed', 'Completed'), ('failed', 'Failed'), ('retry_failed', 'Retry Failed'), ('permanently_failed', 'Permanently Failed')], db_index=True, default='queued', max_length=32),
        ),
    ]
